version: '3.7'
services:
    mongo:
        image: mongo:4.4.0-bionic
        restart: always
        ports:
            - 27017:27017
        environment:
            - MONGO_INITDB_ROOT_USERNAME=${MONGO_DB_ROOT_USER}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_DB_ROOT_PASSWORD}
    application:
        image: rpolnx/node-store:${APP_VERSION}
        restart: always
        ports:
            - 8080:8080
        depends_on:
            - mongo
        environment:
            - MONGO_INITDB_ROOT_USERNAME=${MONGO_DB_ROOT_USER}      #override if needed
            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_DB_ROOT_PASSWORD}  #override if needed
